DeepSeek:
  API_KEY: 
  BASE_URL: https://api.deepseek.com/chat/completions
  MODEL_ID: deepseek-chat
BAILIAN:
  API_KEY: 
  BASE_URL: https://dashscope.aliyuncs.com/compatible-mode/v1
  MODEL_ID: qwen3.5-plus